base_frame: "base_link"
tool_frame: "tool0"
test_links:
- tool0
- forearm_link
- wrist_1_link
- upper_arm_link

minimum_distance: 0.2
reaction_time: 0.15 #0.3

#Information to publish obstacles
publish_obstacles: true
sphere_radius: 0.2
sphere_rgba: [1.0,1.0,1.0,0.2]
