controller_config_file: "$(find ur_robot_driver)/config/ur5e_controllers.yaml" # config file used for defining the ROS-Control controllers.
robot_description_file: "$(find ur_description)/launch/load_ur5e.launch" # Robot description launch file.
kinematics_config: "$(find ur_description)/config/ur5e/default_kinematics.yaml" # Kinematics config file used for calibration correction. This will be used to verify the robot's calibration is matching the robot_description.

debug: false # Debug flag that will get passed on to ur_common.launch
robot_ip: 192.168.150.1 #IP address by which the robot can be reached.
#reverse_ip:  # IP of the driver, if set to empty it will detect it automatically.
reverse_port: 50001 # Port that will be opened by the driver to allow direct communication between the driver and the robot controller.
script_sender_port: 50002 # The driver will offer an interface to receive the program's URScript on this port. If the robot cannot connect to this port, `External Control` will stop immediately.
trajectory_port: 50003 # Port that will be opened by the driver to allow trajectory forwarding.
script_command_port: 50004 # Port that will be opened by the driver to allow forwarding script commands to the robot.
# tf_prefix: "" # tf_prefix used for the robot.

controllers: # Controllers that are activated by default.
  - joint_state_controller 
  - scaled_pos_joint_traj_controller 
  - speed_scaling_state_controller 
  - force_torque_sensor_controller 

stopped_controllers: #Controllers that are initally loaded, but not started.
  - pos_joint_traj_controller
  - joint_group_vel_controller

use_tool_communication: false #On e-Series robots tool communication can be enabled with this argument
tool_voltage: 0 # Tool voltage set at the beginning of the UR program. Only used, when `use_tool_communication` is set to true.
tool_parity: 0 # Parity configuration used for tool communication. Only used, when `use_tool_communication` is set to true.
tool_baud_rate: 115200 # Baud rate used for tool communication. Only used, when `use_tool_communication` is set to true.
tool_stop_bits: 1 # Number of stop bits used for tool communication. Only used, when `use_tool_communication` is set to true.
tool_rx_idle_chars: 1.5 # Number of idle chars in RX channel used for tool communication. Only used, when `use_tool_communication` is set to true.
tool_tx_idle_chars: 3.5 # Number of idle chars in TX channel used for tool communication. Only used, when `use_tool_communication` is set to true.
tool_device_name: "/tmp/ttyUR" # Local device name used for tool communication. Only used, when `use_tool_communication` is set to true.
tool_tcp_port: 54321 # Port on which the robot controller publishes the tool comm interface. Only used, when `use_tool_communication` is set to true.
headless_mode: false # Automatically send URScript to robot to execute. On e-Series this does require the robot to be in 'remote-control' mode. With this, the URCap is not needed on the robot.
ur_hardware_interface_node_required: true # Shut down ros environment if ur_hardware_interface-node dies.
use_spline_interpolation: true # True if splines should be used as interpolation on the robot controller when forwarding trajectory, if false movej or movel commands are used