group_names_map:
  mg1:  ur5e
  mg2:  ur5e

default_planner_config: mg1

mg1:
  type: Multigoal
  max_distance: 2.0
  max_refine_time: 2.0     # time for refine solution
  utopia_tolerance: 0.05  # exit condition for early stop (cost< (1+utopia_tolerance) * distance)
  # max_refine_time: 3.0   # time for refine solution
  # utopia_tolerance: 0.05  # exit condition for early stop (cost< (1+utopia_tolerance) * distance)
  rewire_radius: 4.0
  extend: true
  local_bias: 0.25
  forgetting_factor: 0.999
  tube_radius: 0.02
  warp: false
  warp_once: true
  collision_distance: 0.01

mg2:
  type: Multigoal
  max_distance: 1.0
  inherit_from: mg1